# © Copyright 2019 Yoann MOUGNIBAS
#
# This file is part of ffmpeg-docker.
#
# ffmpeg-docker is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ffmpeg-docker is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ffmpeg-docker. If not, see <http://www.gnu.org/licenses/>

# =============================
# Base image used in gitlab-ci
# =============================
image: mougnibas/ci:latest

# ===========================
# Maven and Docker variables
# ===========================
variables:

  # ================
  # Maven variables
  # ================

  # batch mode
  MAVEN_CLI_OPTS: "--batch-mode"

  # Use this path as m2 repository
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"


  # =================
  # Docker variables
  # =================

  # Use this docker host (started as service)
  DOCKER_HOST: tcp://docker:2375/

  # Use this to prevent performance issue
  DOCKER_DRIVER: overlay2

  # Docker image tag name
  DOCKER_IMAGE_TAG: mougnibas/ffmpeg


# ======================================================================
# Services
#
# Use a "Docker inside Docker" image to get a TCP enabled docker daemon
# ======================================================================
services:
  - docker:dind


# ==========================
# Cache
#
# Store maven related stuff
# ==========================
cache:
  paths:
    - .m2/repository/
    - target/


#================
# Used stages
#================
stages:
  - package
  - deploy


#==========================
# Package the docker image
#==========================
package:
  stage: package
  script:
    - mvn $MAVEN_CLI_OPTS package

#===========================================================================
# Deploy the docker image on docker hub.
#
# Credentials are stored in "Settings / CI/DI / Variables"
# To prevent accidental deployment on push on feature branch, only "master"
# and "tag" will trigger this job.
#===========================================================================
deploy:
  stage: deploy
  script:
    - docker login --username $CI_DOCKERHUB_REGISTRY_USER --password $CI_DOCKERHUB_REGISTRY_PASSWORD
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - tags
